#!/bin/sh
# .claude/skills/icc-tee/scripts/list
# list: one line per tee, "DIR up|down SRC SIDE DST...".
# Up means every lane's copier still has its lane of SRC open to read.
# Copyright (c) 2026 Brian Case. All rights reserved.
# AI contributor: Claude (Anthropic)
#
# MIT License text omitted for brevity, see LICENSE
for d in /tmp/icc-tee-*/; do
  [ -d "$d" ] || continue
  d=${d%/}
  src=$(sed -n 1p "$d/tee"); l=$(sed -n 2p "$d/tee")
  s=up
  for p in $(cat "$d/pid" 2>/dev/null); do
    [ "$(readlink "/proc/$p/fd/0" 2>/dev/null)" = "$src/$l" ] || s=down
    l=$((l + 2))
  done
  echo "$d $s $(paste -sd ' ' < "$d/tee")"
done
